---
version: 3

dependencies:
  galaxy:
    collections:
      - name: community.crypto
      - name: community.general
  python: requirements.txt
  system:
    - gcc [platform:rpm]

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest

additional_build_steps:
  append_base:
    - RUN pip3 install --upgrade pip setuptools

options:
  package_manager_path: /usr/bin/microdnf
...
