---
version: 3

dependencies:
  galaxy:
    collections:
      - name: community.crypto
      - name: community.general
      - name: community.windows
  python:
    - awxkit
    - infoblox-client
    - cryptography
  system:
    - krb5-workstation [platform:rpm]
    - crypto-policies-scripts [platform:rpm]

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest

options:
  package_manager_path: /usr/bin/microdnf
...
